
export const GET_ARTICLE_LIST_REQUEST = 'GET_ARTICLE_LIST_REQUEST';
export const GET_ARTICLE_LIST_SUCCESS = 'GET_ARTICLE_LIST_SUCCESS';
export const GET_ARTICLE_LIST_FAILED = 'GET_ARTICLE_LIST_FAILED';

export const DELETE_ARTICLE_REQUEST = 'DELETE_ARTICLE_REQUEST';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_FAILED = 'DELETE_ARTICLE_FAILED';